version: '3.8'

services:
  kafka:
    image: confluentinc/cp-kafka:8.1.3
    container_name: kafka8
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_KRAFT_MODE: 'true'

      CLUSTER_ID: '1L6g7bsdf-eAKfl--X25wo'
      KAFKA_NODE_ID: 1

      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka1:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1  #  no backup just 1 copy default is 3

      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1 #  no backup just 1 copy default is 3

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092, CONTROLLER://0.0.0.0:9093, INTERNAL://kafka1:19092, EXTERNAL://0.0.0.0:9092, DOCKER://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka1:19092,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092,DOCKER://host.docker.internal:29092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      #stored locally: data-files,broker-logs.controller-metadata
      #KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      KAFKA_LOG_DIRS: jetbrains://pycharm/navigate/reference?project=sample-python-kafka&path=app%2Flogs  #stored locally: data-files,broker-logs.controller-metadata

    volumes:
      - kafka_kraft:/var/lib/kafka/data

volumes:
  kafka_kraft: